project_name: sample-project-5
builds:
  - id: "binary"
    binary: sample-project-5-{{ .Os }}-{{ .Arch }}
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
    no_unique_dist_dir: true

archives:
  - format: binary
